services:
  web:
    build:
      context: ./
      dockerfile: development.Dockerfile
    command: bin/dev-server
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - RAILS_ENV=${RAILS_ENV}
    depends_on:
      db:
        condition: service_healthy
  ci:
    image: ${IMAGE_TAG}
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=changeme
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 5s
      retries: 30

volumes:
  pg_data:
  bundle:
