services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history 
      - RAILS_ENV=${RAILS_ENV}
      - HOST=web
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  chrome:
    command: [ 'sh', 'wrapper-script.sh' ]
    image: headless-chrome
    build: ./chrome
    ports:
      - 9222:9222
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=changeme
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
  bundle:
