name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_TAG: ${{ github.repository }}
  REGISTRY: ghcr.io

jobs:
  build-and-test-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


      - name: Setup env file
        run: cp .env.ci .env

      - name: Prepare test runner
        run: RAILS_ENV=test docker compose run --rm --build web bin/setup-test-runner

      - name: Start containers
        run: docker compose up -d --wait ci

      - name: Run tests
        run: RAILS_ENV=test docker compose run --rm web bin/rake cucumber
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.LATEST_TAG }}

      - name: Push
        id: push
        uses: docker/build-push-action@v6
        # if: github.event_name != 'pull_request'
        with:
          push: true
          # tags: ${{ env.REGISTRY }}/${{ env.LATEST_TAG }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.LATEST_TAG}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
