name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_TAG: mysite:test
  LATEST_TAG: mysite:latest

jobs:
  build-and-test-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}          
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Setup env file
        run: cp .env.ci .env

      - name: Start containers
        run: dcm up -d --wait ci

      - name: Precompile assets
        run: RAILS_ENV=test docker compose run --rm web bin/rails assets:precompile

      - name: Run tests
        run: RAILS_ENV=test docker compose run --rm web bin/rake cucumber

      - name: Push
        uses: docker/build-push-action@v6
        # if: github.event_name != 'pull_request'
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.LATEST_TAG }}
