name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linters:
    runs-on: ubuntu-latest

    env:
      DISABLE_BOOTSNAP: true
      DISABLE_BOOTSNAP_LOAD_PATH_CACHE: true

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run linters
        run: bundle exec rubocop --parallel
      - name: Ruby security checks
        run: bundle exec brakeman -q -w2
          # bundle exec bundler-audit --update

  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Create .env
      run: cp .env.ci .env

    - name: Start containers
      run: docker compose up -d --wait --build --remove-orphans web chrome

    - name: Run tests
      run: docker compose run --rm web bin/rake test:all

    - name: Stop containers
      if: always()
      run: docker compose down --volumes
